name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  # This got renamed to SCCACHE_LOG in newer (unreleased) versions of SCCACHE
  RUST_LOG: 'trace'
  SCCACHE_ERROR_LOG: sccache_log.txt
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install sccache
        id: sccache
        run: python .github/workflows/install-sccache.py

      - name: Start sccache server
        run: sccache --start-server

      - name: Show sccache statistics
        run: sccache --show-stats

      - name: Print sccache log
        if: ${{always()}}
        shell: cmd
        run: |
          cat sccache_log.txt
          echo SCCACHE_DIR='%SCCACHE_DIR%'

      - name: Upload sccache log
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: SccacheLog
          if-no-files-found: error
          path: sccache_log.txt
